- hosts: all
  become: yes
  tasks:
    - name: create the 'jason_gao' user
      user: name=jason_gao append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'jason_gao' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'jason_gao ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the jason_gao user
      authorized_key: user=jason_gao key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
